config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "feeds#index"
  resources :feeds do
    resources :products
  end

  get "/products/search" => "products#search"
  

end

app/models/feed.rb
require 'open-uri'
require 'uri'
require 'paperclip'

class Feed < ActiveRecord::Base
  has_many :products, :dependent => :destroy
  belongs_to :users

  has_attached_file :file

  attr_accessible :title, :file, :file_file_name
  accepts_nested_attributes_for :products

  validates :title, :file, presence: true

  before_save :parse_file

  def parse_file
    tempfile = file.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end

  def parse_xml(doc)
    nodes = doc.xpath('items')

    nodes.each do |node|
      parse_feeds(node)
    end
  end


  def parse_feeds(node)

    if node.node_name.eql? 'items'

      node.elements.each do |node|
        product = Product.new

        node.elements.each do |node|
          product.title = node.text.to_s if node.name.eql? 'title'

          product.price = node.text if node.name.eql? 'price'

          product.campaign = node.text.to_s if node.name.eql? 'campaign_name'
          product.description = node.text.to_s if node.name.eql? 'description'

          product.picture_from_url(node.text.to_s) if node.name.eql? 'image_urls'
        end
      self.products << product
      
      end
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  belongs_to :feeds

  has_attached_file :image, :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :styles => {
    :thumb    => ['100x100#',  :jpg, :quality => 70],
    :preview  => ['480x480#',  :jpg, :quality => 70],
    :large    => ['600>',      :jpg, :quality => 70],
    :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :large    => '-set colorspace sRGB -strip',
    :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }

  attr_accessible :feed_id, :title, :price, :campaign, :description, :image
  validates :title, :price, :description, presence: :true

  def picture_from_url(url)
    self.image = URI.parse(url)
    self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  has_many :feeds

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery 
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :js

  handles_sortable_columns

  def new
    @feed = Feed.new
  end


  def create
    @feed = current_user.feeds.new(feed_params)
    count = @feed.products.count
      if @feed.save
        Appmail.new_feed(current_user, @feed.title, count).deliver
        redirect_to @feed,  success: 'Un nou feed a fost creat.' 
      else
        render 'new'
      end
  end


  def show
    @feed = current_user.feeds.find(params[:id])
    order = sortable_column_order
    @products = @feed.products.order(order).paginate(page: params[:page], per_page: 5)
  end

  def index
    @feeds = current_user.feeds.order(created_at: :desc)
  end

  def destroy
    @feed = current_user.feeds.find(params[:id])
    count = @feed.products.count

    Appmail.delete_feed(current_user, @feed.title, count).deliver

    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, danger: 'Un feed a fost sters.' }
    end
  end

  private
  def feed_params
    params.require(:feed).permit(:title, :file, :file_file_name)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_user!
  skip_filter :verify_authenticity_token, :create
  respond_to :js, :html, :json


  def new
    @feed = Feed.find(params[:feed_id])
    @product = @feed.products.build
  end

  def create
    @feed = Feed.find(params[:feed_id])
    @product = @feed.products.build(product_params)

    if @product.save
      Appmail.new_product(current_user, @feed.title, @product.title).deliver
      respond_to do |format|
        format.html {redirect_to feed_path(@feed), success: 'Un nou produs a fost adaugat.' }
        format.js {}
      end
    else
      render "new"
    end
  end

  def edit
    @feed = Feed.find(params[:feed_id])
    @product = Product.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:feed_id])
    @product = Product.find(params[:id])

    if @product.update(product_params)
      Appmail.update_product(current_user, @feed.title, @product.title).deliver
      redirect_to feed_path(@feed), info: 'Un produs a fost modificat.' 
    else
      render "edit" 
    end
  end

  def destroy
    @feed = Feed.find(params[:feed_id])
    @product = @feed.products.find(params[:id])
    Appmail.delete_product(current_user, @feed.title, @product.title).deliver
    @product.destroy
    redirect_to feed_path(@feed), danger: 'Un produs a fost sters.' 
  end

  def search
    if(params[:search] and params[:search_by])
      column_name = params[:search_by].to_s + " LIKE ?"
      @products =  Product.where(column_name, "%#{params[:search]}%").paginate(page: params[:page], per_page: 5)
    else
      @products = Product.all.paginate(page: params[:page], per_page: 5)
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :price, :campaign, :image, :description,:feed_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/appmail/delete_feed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h4>A fost sters un feed: </h4>
    <p>
      Titlul: <%= @title %>
    </p>

     <p>
      Numarul de produse: <%= @count %>
    </p>
    
  </body>
</html>

app/views/appmail/delete_product.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h4> Un produs a fost sters. </h4>
    <p>
      Titlu feed: <%= @title_feed %>
    </p>

     <p>
      Titlu produs: <%= @title_product %>
    </p>
    
  </body>
</html>

app/views/appmail/new_feed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h4>A fost creat un nou feed: </h4>
    <p>
      Titlul: <%= @title %>
    </p>

     <p>
      Numarul de produse: <%= @count %>
    </p>
    
  </body>
</html>

app/views/appmail/new_product.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h4> Un produs a fost adaugat. </h4>
    <p>
      Titlu feed: <%= @title_feed %>
    </p>

     <p>
      Titlu produs: <%= @title_product %>
    </p>
    
  </body>
</html>

app/views/appmail/update_product.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h4> Un produs a fost modificat. </h4>
    <p>
      Titlu feed: <%= @title_feed %>
    </p>

     <p>
      Titlu produs: <%= @title_product %>
    </p>
    
  </body>
</html>

app/views/feeds/_form.html.erb
<%= form_for :feed, url: feeds_path,  :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'layouts/errors', object: @feed %>

  <div class="form-group">
    <%= f.label :title, :class => 'form-label' %>
    <div class="forms">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :file, :class => 'form-label' %>
    <div class="control">
      <%= f.file_field :file %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-success' %>
  </div>

<% end %>

app/views/feeds/index.html.erb
<div class="page-title">
  <h1>All feeds</h1>
</div>

<% if @feeds.length == 0%>

  <p> No feed to display. </p>
  <%= link_to 'Create feed', new_feed_path, :class => "btn btn-success"  %> 

<% else %>

<table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Number of products</th>
      
      </tr>
    </thead>

    <tbody>
      <% @feeds.each do |feed| %>
        <tr>
          <td><%= feed.title %></td>
          <td><%= feed.products.count %></td>

          <td><%= link_to 'Show feed', feed_path(feed), :class => "btn btn-primary" %> </td>

          <td><%= link_to 'Delete feed',  feed,  method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"%> </td>
        </tr>
      <% end %>
    </tbody>
</table>

<% end %>

app/views/feeds/new.html.erb
<div class="page-title"> 
  <h1>New feed</h1>
</div>


<%= render 'form' %>

app/views/feeds/show.html.erb
<h2 class="title">
<%= @feed.title %>
</h2>

<%= link_to 'Add new product', {:controller =>  "products", :action  => "new", :feed_id => @feed.id }, :class => "btn btn-success"%>


<div class="slider">
  <% @products.each do |product| %>
  <div class="slider-details">
    <%= link_to image_tag(product.image.url(:thumb)), product.image.url%>

    <%= link_to '',edit_feed_product_path(@feed, product), :class => "glyphicon glyphicon-pencil" %>

    <%= link_to '', feed_product_path(@feed, product),
    method: :delete,
    data: { confirm: 'Are you sure?' } , :class => "glyphicon glyphicon-trash" %>
    </div>
  <% end %>
</div>

<p class="sort_links">
  Sort by: 
  <%= sortable_column "Title", :column => "title" %>
  <%= sortable_column "Price", :column => "price" %>
  <%= sortable_column "Created date", :column => "created_at" %>
<p>

<div class="products">
<%= render @products %>
</div>


<%= will_paginate @products %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert fade in alert-danger alert-dismissable"><button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParaleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'fonts', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script type="text/javascript">
        $(document).ready(function(){
            $(".slider").owlCarousel();
        });
    </script>


  <%= csrf_meta_tags %>


</head>
<body>

<nav role="navigation" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">2performantApp</a>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li><%= link_to('Create feed', new_feed_path, :class => "line1_p") %> </li>
                    <li><%= link_to('Search product', '/products/search', :class => "line1_p") %> </li>
                    <li><%= link_to('All feeds', feeds_path, :class => "line1_p") %> </li>
                    <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete', :class => "line1_p") %> </li>
                <%else%>
                    <li><%= link_to('Login', new_user_session_path, :class => "line1_p") %> </li>
                    <li><%= link_to('Register', new_user_registration_path, :class => "line1_p") %> </li>

                <%end%> 
            </ul>


        </div>
    </div>
</nav>

<div class='body-container'>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable fade in">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= value %>
       </div>
   <% end %>

  <%= yield %>
  </div>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for([@feed, @product], :html => { :class => 'form-horizontal' } ) do |f| %>
 <%= render 'layouts/errors', object: @product %>
  <div class="form-group">
    <%= f.label :title, :class => 'form-label' %>
    <div class="forms">
      <%= f.text_field :title%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :Campaign_name, :class => 'form-label' %>
    <div class="control">
      <%= f.text_field :campaign %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :price, :class => 'form-label' %>
    <div class="control">
      <%= f.text_field :price %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :description, :class => 'form-label' %>
    <div class="control">
      <%= f.text_area :description, :row => 20, :cols => 50 %>
    </div>

   <div class="form-group">
    <%= f.label :image, :class => 'form-label' %>
    <div class="control">
      <%= f.file_field :image %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-success' %>
  </div>
  
  <% end %>

app/views/products/_product.html.erb
<div class="row show-product">

  <div class="col-lg-2">
    <%= link_to image_tag(product.image.url(:thumb)), product.image.url%>
  </div>

 <div class='col-lg-9'>
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

   <p>
    <strong>Campaign name:</strong>
    <%= product.campaign %>
  </p>

 
  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

	<p>
	<%= link_to 'Edit product',edit_feed_product_path(@feed, product), :class => "btn btn-primary" %>

	  <%= link_to 'Delete product', feed_product_path(@feed, product),
	               method: :delete,
	               data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
	</p>

  </div>
  </div>



 

app/views/products/edit.html.erb
<div class="page-title"> 
	<h1>Edit product</h1>
 </div>

 
<%= link_to image_tag(@product.image.url(:thumb)), @product.image.url%>

<%= render 'form' %>
 

app/views/products/new.html.erb
<h3>Add a product:</h3>

<%= render "form"%>

app/views/products/search.html.erb
<%= form_tag '/products/search', method: :get do %>
Search by <%= select_tag "search_by", options_for_select([ "Title", "Price" ]) %>
<%= text_field_tag :search, params[:search], placeholder: "Search" %>

<%= submit_tag "Search" %>

<% end %>

 <% @products.each do |product| %>
<div class="row show-product">

  <div class="col-lg-2">
    <%= link_to image_tag(product.image.url(:thumb)), product.image.url%>
  </div>

 <div class='col-lg-9'>
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

   <p>
    <strong>Campaign name:</strong>
    <%= product.campaign %>
  </p>

 
  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  </div>
  </div>

<% end %>

<%= will_paginate @products %>